//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Casgem_Portfolio.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblContact
    {
        public int ContactId { get; set; }
        public string ContactTel { get; set; }
        public string ContactMail { get; set; }
        public string ContactAdress { get; set; }
        public string ContactMaps { get; set; }
    }
}
