//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Casgem_Portfolio.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblReference
    {
        public int ReferenceId { get; set; }
        public string ReferenceImgUrl { get; set; }
        public string ReferenceNameSurname { get; set; }
        public string ReferenceBusinessName { get; set; }
        public string ReferenceDescription { get; set; }
    }
}
